/**
 * DATOS SEMILLA Y DEMO — PORTAL DE CLIENTES (ERP LABORAPY)
 * Empresas paraguayas modelo con nómina completa, contratos y comprobantes
 */

import type {
  EmpresaCliente,
  ClienteUsuario,
  Empleado,
  ContratoTrabajo,
  DocumentoCumplimiento,
  RegistroVacacion,
  RegistroMaternidad,
  AdendaContrato,
} from '../types/clientPortal';

export const DEMO_EMPRESAS: EmpresaCliente[] = [
  {
    id: 'emp_guarani_001',
    ruc: '80098765',
    dv: '4',
    razonSocial: 'COMERCIAL & LOGÍSTICA GUARANÍ S.A.',
    nombreFantasia: 'Logística Guaraní',
    actividadEconomica: 'Distribución y logística nacional de mercaderías',
    direccion: 'Avda. Eusebio Ayala Km 4.5 c/ De la Victoria, Asunción',
    telefono: '(021) 555-1234 / (0981) 123-456',
    emailCorporativo: 'contacto@logisticaguarani.com.py',
    nroPatronalIps: 'IPS-784512-PY',
    nroPatronalMtess: 'MTESS-2023-9941',
    representanteLegalNombre: 'Ing. Carlos Alberto Duarte Giménez',
    representanteLegalCi: '2.845.678',
    configAntiguedad: {
      umbralAnhosHombres: 9,
      umbralAnhosMujeres: 8,
      alertarDiasAntes: 60,
    },
    activo: true,
    createdAt: '2025-01-10T08:00:00Z',
  },
  {
    id: 'emp_asuncion_002',
    ruc: '80123456',
    dv: '7',
    razonSocial: 'SERVICIOS INTEGRALES ASUNCIÓN S.R.L.',
    nombreFantasia: 'Asunción Consulting & Services',
    actividadEconomica: 'Consultoría y prestación de servicios empresariales',
    direccion: 'Aviadores del Chaco 2050, Edificio World Trade Center, Asunción',
    telefono: '(021) 600-7890',
    emailCorporativo: 'administracion@asuncionservices.com.py',
    nroPatronalIps: 'IPS-332190-PY',
    nroPatronalMtess: 'MTESS-2024-1188',
    representanteLegalNombre: 'Lic. María Elena Benítez Villalba',
    representanteLegalCi: '3.456.789',
    activo: true,
    createdAt: '2025-06-01T08:00:00Z',
  }
];

export const DEMO_USUARIOS: ClienteUsuario[] = [
  {
    id: 'usr_guarani_admin',
    clienteId: 'emp_guarani_001',
    email: 'cliente@laborapy.com', // Usuario demo predeterminado
    nombreContacto: 'Lic. Rodrigo Solís',
    cargoContacto: 'Gerente Administrativo & Finanzas',
    telefono: '(0981) 777-888',
    rol: 'cliente_admin',
    activo: true,
  },
  {
    id: 'usr_asuncion_admin',
    clienteId: 'emp_asuncion_002',
    email: 'rrhh@asuncionservices.com.py',
    nombreContacto: 'Lic. Natalia Ortiz',
    cargoContacto: 'Jefa de Gestión de Personas',
    telefono: '(0982) 444-555',
    rol: 'cliente_admin',
    activo: true,
  }
];

export const DEMO_EMPLEADOS: Empleado[] = [
  {
    id: 'emp_01',
    clienteId: 'emp_guarani_001',
    ci: '4.567.890',
    nombres: 'Jorge David',
    apellidos: 'Ramírez Silvero',
    fechaNacimiento: '1992-04-15',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Casado/a',
    sexo: 'M',
    domicilio: 'Barrio Sajonia, Calle Dr. Coronel 450, Asunción',
    telefono: '(0971) 321-654',
    email: 'jorge.ramirez@gmail.com',
    hijosMenores: 2, // Cobrará bonificación familiar (2 * 5% de salario mínimo)
    cargo: 'Supervisor de Logística & Flota',
    departamento: 'Operaciones',
    fechaIngreso: '2021-03-01',
    salarioBase: 4800000,
    modalidadPago: 'mensual',
    nroIps: '4567890-01',
    estado: 'activo',
    periodoPruebaDias: 60,
    vacacionesCausadasAcumuladas: 18,
    vacacionesTomadas: 6,
    notas: 'Empleado de confianza. Conduce vehículos de la empresa.',
    createdAt: '2021-03-01T08:00:00Z',
  },
  {
    id: 'emp_02',
    clienteId: 'emp_guarani_001',
    ci: '5.123.456',
    nombres: 'Claudia Elizabeth',
    apellidos: 'González Cardozo',
    fechaNacimiento: '1996-08-20',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Soltero/a',
    sexo: 'F',
    domicilio: 'San Lorenzo, Avda. del Agrónomo 1230',
    telefono: '(0983) 987-654',
    email: 'claudia.gonzalez@gmail.com',
    hijosMenores: 0,
    cargo: 'Analista de Facturación & Cobranzas',
    departamento: 'Administración',
    fechaIngreso: '2023-07-15',
    salarioBase: 3500000,
    modalidadPago: 'mensual',
    nroIps: '5123456-01',
    estado: 'activo',
    periodoPruebaDias: 30,
    vacacionesCausadasAcumuladas: 12,
    vacacionesTomadas: 0,
    registroMaternidadId: 'mat_02',
    estadoMaternidad: 'lactancia_obligatoria',
    createdAt: '2023-07-15T08:00:00Z',
  },
  {
    id: 'emp_03',
    clienteId: 'emp_guarani_001',
    ci: '3.987.654',
    nombres: 'Víctor Manuel',
    apellidos: 'Torres Benítez',
    fechaNacimiento: '1988-11-05',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Casado/a',
    sexo: 'M',
    domicilio: 'Lambaré, Calle Defensores del Chaco 890',
    telefono: '(0961) 555-444',
    email: 'victor.torres@gmail.com',
    hijosMenores: 3,
    cargo: 'Chofer Repartidor de Cargas Pesadas',
    departamento: 'Distribución',
    fechaIngreso: '2019-02-10',
    salarioBase: 3200000,
    modalidadPago: 'mensual',
    nroIps: '3987654-01',
    estado: 'activo',
    periodoPruebaDias: 30,
    vacacionesCausadasAcumuladas: 18,
    vacacionesTomadas: 18,
    createdAt: '2019-02-10T08:00:00Z',
  },
  {
    id: 'emp_04',
    clienteId: 'emp_guarani_001',
    ci: '6.234.567',
    nombres: 'Esteban Andrés',
    apellidos: 'Rivarola Mendoza',
    fechaNacimiento: '2001-01-18',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Soltero/a',
    sexo: 'M',
    domicilio: 'Fernando de la Mora, Zona Sur',
    telefono: '(0985) 111-222',
    email: 'esteban.rivarola@outlook.com',
    hijosMenores: 0,
    cargo: 'Auxiliar de Depósito & Picking',
    departamento: 'Operaciones',
    fechaIngreso: '2026-08-18', // Ingresó hace pocas semanas -> ¡EN PERÍODO DE PRUEBA!
    salarioBase: 2800000, // Salario mínimo redondeado
    modalidadPago: 'mensual',
    nroIps: '6234567-01',
    estado: 'prueba',
    periodoPruebaDias: 30,
    vacacionesCausadasAcumuladas: 0,
    vacacionesTomadas: 0,
    notas: 'Contratado a prueba. Vencimiento en septiembre 2026.',
    createdAt: '2026-08-18T08:00:00Z',
  },
  {
    id: 'emp_05',
    clienteId: 'emp_guarani_001',
    ci: '5.876.543',
    nombres: 'Silvia Beatriz',
    apellidos: 'Vargas Quintana',
    fechaNacimiento: '1998-09-30',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Soltero/a',
    sexo: 'F',
    domicilio: 'Luque, Cuarto Barrio',
    telefono: '(0972) 888-999',
    email: 'silvia.vargas@yahoo.com',
    hijosMenores: 1,
    cargo: 'Asistente de Atención al Cliente & Rastreos',
    departamento: 'Comercial',
    fechaIngreso: '2024-05-02',
    salarioBase: 2900000,
    modalidadPago: 'mensual',
    nroIps: '5876543-01',
    estado: 'activo',
    periodoPruebaDias: 30,
    vacacionesCausadasAcumuladas: 12,
    vacacionesTomadas: 0,
    registroMaternidadId: 'mat_01',
    estadoMaternidad: 'embarazada',
    createdAt: '2024-05-02T08:00:00Z',
  },
  {
    id: 'emp_06',
    clienteId: 'emp_guarani_001',
    ci: '2.345.678',
    nombres: 'Gustavo Adolfo',
    apellidos: 'Villalba Rolón',
    fechaNacimiento: '1984-06-12',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Casado/a',
    sexo: 'M',
    domicilio: 'Asunción, Barrio Herrera',
    telefono: '(0981) 654-987',
    email: 'gustavo.villalba@empresa.com.py',
    hijosMenores: 2,
    cargo: 'Jefe de Operaciones & Depósito Central',
    departamento: 'Logística',
    fechaIngreso: '2017-04-10', // En 2026: ~9.4 años -> ¡Alerta preventivo 9 años hombres (Art. 94)!
    salarioBase: 5800000,
    modalidadPago: 'mensual',
    nroIps: '2345678-01',
    estado: 'activo',
    periodoPruebaDias: 60,
    vacacionesCausadasAcumuladas: 18,
    vacacionesTomadas: 0,
    notas: 'Antigüedad 9 años y 5 meses. Próximo a adquirir estabilidad propia (Art. 94 a los 10 años).',
    createdAt: '2017-04-10T08:00:00Z',
  },
  {
    id: 'emp_07',
    clienteId: 'emp_guarani_001',
    ci: '3.123.456',
    nombres: 'Mirtha Raquel',
    apellidos: 'Giménez Benítez',
    fechaNacimiento: '1989-11-25',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Casado/a',
    sexo: 'F',
    domicilio: 'Lambaré, Barrio Santa Lucía',
    telefono: '(0971) 444-333',
    email: 'mirtha.gimenez@empresa.com.py',
    hijosMenores: 1,
    cargo: 'Coordinadora de Créditos y Finanzas',
    departamento: 'Administración',
    fechaIngreso: '2018-05-15', // En 2026: ~8.3 años -> ¡Alerta preventivo 8 años mujeres (Art. 94)!
    salarioBase: 5100000,
    modalidadPago: 'mensual',
    nroIps: '3123456-01',
    estado: 'activo',
    periodoPruebaDias: 60,
    vacacionesCausadasAcumuladas: 18,
    vacacionesTomadas: 6,
    registroMaternidadId: 'mat_03',
    estadoMaternidad: 'lactancia_extendida',
    notas: 'Antigüedad 8 años y 3 meses. Evaluación de carrera y estabilidad en curso.',
    createdAt: '2018-05-15T08:00:00Z',
  },
  {
    id: 'emp_08',
    clienteId: 'emp_guarani_001',
    ci: '1.890.123',
    nombres: 'Bernardo',
    apellidos: 'Benítez Galeano',
    fechaNacimiento: '1976-03-08',
    nacionalidad: 'Paraguaya',
    estadoCivil: 'Casado/a',
    sexo: 'M',
    domicilio: 'Asunción, Barrio San Cristóbal',
    telefono: '(0982) 111-999',
    email: 'bernardo.benitez@empresa.com.py',
    hijosMenores: 0,
    cargo: 'Gerente Operativo Senior',
    departamento: 'Dirección',
    fechaIngreso: '2013-10-01', // En 2026: ~12.9 años -> ¡Estabilidad especial Art. 94 ya adquirida (>10 años)!
    salarioBase: 8500000,
    modalidadPago: 'mensual',
    nroIps: '1890123-01',
    estado: 'activo',
    periodoPruebaDias: 60,
    vacacionesCausadasAcumuladas: 30,
    vacacionesTomadas: 15,
    notas: 'Empleado con estabilidad especial laboral adquirida (Art. 94). Más de 10 años continuos.',
    createdAt: '2013-10-01T08:00:00Z',
  }
];

export const DEMO_CONTRATOS: ContratoTrabajo[] = [
  {
    id: 'cto_01',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_01',
    tipoContrato: 'indefinido',
    fechaInicio: '2021-03-01',
    periodoPruebaDias: 60,
    salarioPactado: 4800000,
    jornadaLaboral: '48 horas semanales (Lunes a Viernes 07:30 a 17:00, Sábados 08:00 a 12:00)',
    horarioInicio: '07:30',
    horarioFin: '17:00',
    lugarPrestacion: 'Sede Central - Asunción, Paraguay',
    clausulasAdicionales: 'Confidencialidad de clientes y rutas de distribución. Uso de vehículo corporativo.',
    estado: 'firmado',
    createdAt: '2021-03-01T08:00:00Z',
  },
  {
    id: 'cto_04',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_04',
    tipoContrato: 'indefinido',
    fechaInicio: '2026-08-18',
    periodoPruebaDias: 30,
    salarioPactado: 2800000,
    jornadaLaboral: '48 horas semanales (Lunes a Sábado)',
    horarioInicio: '08:00',
    horarioFin: '17:00',
    lugarPrestacion: 'Centro Logístico Km 4.5, Asunción',
    clausulasAdicionales: 'Sujeto a período de prueba de 30 días según Art. 58 del Código del Trabajo.',
    estado: 'firmado',
    createdAt: '2026-08-18T08:00:00Z',
  }
];

export const DEMO_DOCUMENTOS: DocumentoCumplimiento[] = [
  {
    id: 'doc_reop_2026_07',
    clienteId: 'emp_guarani_001',
    tipo: 'comprobante_reop_mensual',
    periodo: '2026-07',
    titulo: 'Constancia de Comunicación Mensual REOP - Julio 2026',
    archivoNombre: 'MTESS_REOP_JULIO_2026_GUARANI.pdf',
    nroTransaccionOficial: 'REOP-PY-2026-07-88914',
    fechaPresentacion: '2026-08-08',
    notas: 'Declaración mensual de salarios y nómina presentada en tiempo y forma.',
    createdAt: '2026-08-08T10:30:00Z',
  },
  {
    id: 'doc_ips_2026_07',
    clienteId: 'emp_guarani_001',
    tipo: 'extracto_ips',
    periodo: '2026-07',
    titulo: 'Extracto Oficial de Aportes IPS - Julio 2026',
    archivoNombre: 'IPS_EXTRACTO_JULIO_2026_784512.pdf',
    nroTransaccionOficial: 'EXT-IPS-202607-44120',
    fechaPresentacion: '2026-08-18',
    montoAbonado: 4386000,
    notas: 'Extracto liquidado y cancelado mediante débito bancario BNF.',
    createdAt: '2026-08-18T14:15:00Z',
  },
  {
    id: 'doc_libro_2025',
    clienteId: 'emp_guarani_001',
    tipo: 'comprobante_libro_anual_mtess',
    periodo: '2025',
    titulo: 'Constancia de Homologación de Libros Anuales MTESS (Ejercicio 2025)',
    archivoNombre: 'MTESS_LIBROS_ANUALES_2025_CERTIFICADO.pdf',
    nroTransaccionOficial: 'HOM-MTESS-2025-004512',
    fechaPresentacion: '2026-04-12',
    montoAbonado: 250000,
    notas: 'Libros de Sueldos y Jornales, Empleados y Obreros y RGPO homologados sin multas.',
    createdAt: '2026-04-12T09:00:00Z',
  }
];

export const DEMO_VACACIONES: RegistroVacacion[] = [
  {
    id: 'vac_01',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_01', // Jorge Ramírez (ingreso 2021)
    periodoAnho: 2025,
    diasCorrespondientes: 18,
    fechaInicioReal: '2026-07-06',
    fechaFinReal: '2026-07-11',
    diasUsufructuadosReal: 6,
    diasPendientesReal: 12,
    estadoReal: 'fraccionado',
    fechaLimiteUsufructo: '2026-09-01',
    comunicadoMtess: true,
    mesComunicacionMtess: '2026-07',
    fechaComunicacionMtess: '2026-08-05',
    nroComprobanteMtess: 'REOP-VAC-202607-0091',
    diasComunicadosMtess: 6,
    notas: 'Usufructo fraccionado de 6 días en julio. Quedan 12 días para el período de verano.',
    createdAt: '2026-06-15T08:00:00Z',
  },
  {
    id: 'vac_02',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_02', // Claudia González (ingreso 2023)
    periodoAnho: 2025,
    diasCorrespondientes: 12,
    fechaInicioReal: '2026-09-14',
    fechaFinReal: '2026-09-25',
    diasUsufructuadosReal: 12,
    diasPendientesReal: 0,
    estadoReal: 'en_curso',
    fechaLimiteUsufructo: '2027-01-15',
    comunicadoMtess: false,
    notas: 'Programadas para usufructo completo en septiembre. Pendiente de declaración mensual REOP al cierre.',
    createdAt: '2026-08-25T10:00:00Z',
  },
  {
    id: 'vac_03',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_06', // Gustavo Villalba (9 años)
    periodoAnho: 2025,
    diasCorrespondientes: 18,
    diasUsufructuadosReal: 0,
    diasPendientesReal: 18,
    estadoReal: 'pendiente',
    fechaLimiteUsufructo: '2026-10-10',
    comunicadoMtess: false,
    notas: 'Pendiente de coordinación de fechas con la jefatura de operaciones.',
    createdAt: '2026-04-10T08:00:00Z',
  },
  {
    id: 'vac_04',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_07', // Mirtha Giménez (8 años)
    periodoAnho: 2025,
    diasCorrespondientes: 18,
    fechaInicioReal: '2026-01-12',
    fechaFinReal: '2026-01-23',
    diasUsufructuadosReal: 12,
    diasPendientesReal: 6,
    estadoReal: 'fraccionado',
    fechaLimiteUsufructo: '2026-11-15',
    comunicadoMtess: true,
    mesComunicacionMtess: '2026-01',
    fechaComunicacionMtess: '2026-02-06',
    nroComprobanteMtess: 'REOP-VAC-202601-0044',
    diasComunicadosMtess: 12,
    notas: 'Gozó 12 días en enero. Saldo de 6 días pendiente para octubre.',
    createdAt: '2025-12-20T08:00:00Z',
  }
];

export const DEMO_MATERNIDAD: RegistroMaternidad[] = [
  {
    id: 'mat_01',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_05', // Silvia Beatriz Vargas Quintana
    estado: 'embarazada',
    fechaNotificacionEmbarazo: '2026-04-15',
    fechaProbablePartoFPP: '2026-09-23',
    fechaInicioReposo: '2026-09-09', // FPP - 14 días (38 semanas de gestación)
    fechaFinReposo: '2027-01-12',    // 126 días corridos (18 semanas Ley 5508/15)
    fechaReincorporacionTrabajo: '2027-01-13',
    subsidioIpsEstado: 'tramitado',
    modalidadLactancia: 'salida_temprana_90min',
    fechaFinLactanciaObligatoria: '2027-03-23', // Nacimiento estimado + 6 meses
    deseaExtensionLactancia: true,
    fechaLimiteMaximoLactancia24Meses: '2028-09-23', // 24 meses / 2 años
    certificadosTrimestrales: [],
    fueroMaternalActivo: true,
    fechaFinEstimadaFuero: '2027-03-23',
    notas: 'Notificación fehaciente con ecografía prenatal. Trámite de subsidio 100% IPS REI cargado con éxito. Fuero maternal blindado.',
    createdAt: '2026-04-15T08:00:00Z',
    updatedAt: '2026-09-01T08:00:00Z',
  },
  {
    id: 'mat_02',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_02', // Claudia Elizabeth González Cardozo
    estado: 'lactancia_obligatoria',
    fechaNotificacionEmbarazo: '2025-10-01',
    fechaProbablePartoFPP: '2026-03-25',
    fechaPartoReal: '2026-03-25',
    fechaInicioReposo: '2026-03-11',
    fechaFinReposo: '2026-07-14',    // 126 días corridos
    fechaReincorporacionTrabajo: '2026-07-15',
    subsidioIpsEstado: 'cobrado_por_asegurada',
    modalidadLactancia: 'dos_pausas_45min',
    fechaFinLactanciaObligatoria: '2026-09-25', // Cumple 6 meses en septiembre 2026 -> ALERTA PROXIMO VENCIMIENTO
    deseaExtensionLactancia: true,
    fechaLimiteMaximoLactancia24Meses: '2028-03-25',
    certificadosTrimestrales: [],
    proximoVencimientoCertificado: '2026-09-25',
    fueroMaternalActivo: true,
    fechaFinEstimadaFuero: '2026-09-25',
    notas: 'Reincorporada tras 18 semanas de reposo. Usufructúa dos descansos de 45 min diarios. Vence período obligatorio de 6 meses el 25/09/2026.',
    createdAt: '2025-10-01T08:00:00Z',
    updatedAt: '2026-07-15T08:00:00Z',
  },
  {
    id: 'mat_03',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_07', // Mirtha Raquel Giménez Benítez
    estado: 'lactancia_extendida',
    fechaNotificacionEmbarazo: '2025-05-10',
    fechaProbablePartoFPP: '2025-10-10',
    fechaPartoReal: '2025-10-10',
    fechaInicioReposo: '2025-09-26',
    fechaFinReposo: '2026-01-29',    // 126 días corridos
    fechaReincorporacionTrabajo: '2026-01-30',
    subsidioIpsEstado: 'cobrado_por_asegurada',
    modalidadLactancia: 'entrada_tardia_90min',
    fechaFinLactanciaObligatoria: '2026-04-10',
    deseaExtensionLactancia: true,
    fechaLimiteMaximoLactancia24Meses: '2027-10-10',
    certificadosTrimestrales: [
      {
        id: 'cert_mat03_1',
        nroTrimestre: 1,
        fechaPresentacion: '2026-04-08',
        fechaVencimiento: '2026-07-10',
        medicoPediatra: 'Dra. Sandra Peralta (Reg. Prof. 12.845)',
        registroProfesional: '12.845',
        observaciones: 'Lactancia materna exclusiva continuada.',
        esVigente: false,
      },
      {
        id: 'cert_mat03_2',
        nroTrimestre: 2,
        fechaPresentacion: '2026-07-08',
        fechaVencimiento: '2026-10-10',
        medicoPediatra: 'Dra. Sandra Peralta (Reg. Prof. 12.845)',
        registroProfesional: '12.845',
        observaciones: 'Lactancia complementaria activa.',
        esVigente: true,
      }
    ],
    proximoVencimientoCertificado: '2026-10-10',
    fueroMaternalActivo: true,
    fechaFinEstimadaFuero: '2026-10-10',
    notas: 'Prórroga trimestral de lactancia concedida según Ley N.º 7097/23. Próximo certificado pediátrico a presentar antes del 10/10/2026.',
    createdAt: '2025-05-10T08:00:00Z',
    updatedAt: '2026-07-08T08:00:00Z',
  }
];

export const DEMO_ADENDAS: AdendaContrato[] = [
  {
    id: 'ade_01',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_02', // Claudia Elizabeth González Cardozo
    fechaContratoOriginal: '2023-07-15',
    nroAdenda: 1,
    motivo: 'modificacion_salarial',
    tituloAdenda: 'Modificación de Remuneración y Régimen de Comisiones',
    fechaEmision: '2026-02-01',
    fechaVigencia: '2026-02-01',
    salarioAnterior: 3000000,
    nuevoSalario: 3500000,
    detalleComisiones: '2% sobre facturación neta cobrada dentro del mes + Gs. 300.000 por cumplimiento del 100% de metas comerciales.',
    estado: 'firmado',
    createdAt: '2026-02-01T08:30:00Z',
  },
  {
    id: 'ade_02',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_01', // Carlos Benítez
    fechaContratoOriginal: '2021-03-01',
    nroAdenda: 1,
    motivo: 'traslado_sucursal',
    tituloAdenda: 'Traslado de Establecimiento Laboral a Sucursal CDE',
    fechaEmision: '2026-01-15',
    fechaVigencia: '2026-02-01',
    lugarAnterior: 'Casa Central - Avda. Aviadores del Chaco 2050, Asunción',
    nuevoLugar: 'Sucursal Este - Avda. Monseñor Rodríguez Km 4, Ciudad del Este',
    compensacionTraslado: 'Asignación no remunerativa de Gs. 1.200.000 mensuales en concepto de gastos de movilidad y radicación transitoria.',
    estado: 'firmado',
    createdAt: '2026-01-15T09:00:00Z',
  },
  {
    id: 'ade_03',
    clienteId: 'emp_guarani_001',
    empleadoId: 'emp_03', // Víctor Manuel Torres Benítez
    fechaContratoOriginal: '2022-01-10',
    nroAdenda: 1,
    motivo: 'confidencialidad_nda',
    tituloAdenda: 'Pacto Especial de Confidencialidad, Secreto Comercial y No Concurrencia',
    fechaEmision: '2026-03-01',
    fechaVigencia: '2026-03-01',
    alcanceConfidencialidad: 'Bases de datos de clientes, código fuente, políticas de pricing, algoritmos y estrategias comerciales corporativas.',
    penalidadIncumplimiento: 'Indemnización de daños y perjuicios conforme a la legislación civil y causal de despido justificado bajo Art. 81 inc. c y h del Código del Trabajo.',
    estado: 'firmado',
    createdAt: '2026-03-01T10:00:00Z',
  },
];


